# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('code_manager', '0001_initial'),
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sta_dt', models.DateField()),
                ('end_dt', models.DateField()),
                ('first_approval', models.CharField(max_length=2)),
                ('last_approval', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_manager.Code_model', to_field='cd')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.Register_model')),
            ],
            options={
                'db_table': 't_vacation',
            },
        ),
    ]
