# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code_model',
            fields=[
                ('grp_cd', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cd', models.CharField(max_length=10, primary_key=True)),
                ('cd_nm', models.CharField(max_length=10)),
                ('option', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 't_code',
            },
        ),
    ]
