# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='팀 고유 아이디')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='아이디')),
                ('name', models.CharField(max_length=10, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('team', models.CharField(max_length=32, verbose_name='소속')),
                ('position', models.CharField(choices=[('a', '대표'), ('b', '팀장'), ('c', '과장'), ('d', '대리'), ('e', '주임'), ('f', '사원'), ('g', '인턴')], default='g', max_length=2, verbose_name='직급')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='생일')),
                ('date_joined', models.DateField(blank=True, null=True, verbose_name='입사일')),
                ('date_exited', models.DateField(blank=True, null=True, verbose_name='퇴사일')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='관리자 여부')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스태브 여부')),
                ('is_active', models.BooleanField(default=False, verbose_name='활성화 여부')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
