# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_exited',
            field=models.DateField(blank=True, null=True, verbose_name='퇴사일'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_joined',
            field=models.DateField(blank=True, null=True, verbose_name='입사일'),
        ),
    ]
