# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171109_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.Team', verbose_name='소속'),
        ),
    ]
