# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171108_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='스태브 여부'),
        ),
    ]
