# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_myuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='position',
            field=models.CharField(choices=[('a', '대표'), ('b', '팀장'), ('c', '과장'), ('d', '대리'), ('e', '주임'), ('f', '사원'), ('g', '인턴')], default='g', max_length=2, verbose_name='직급'),
        ),
    ]
