# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171110_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserCode', verbose_name='직급'),
        ),
    ]
