# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171110_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='v_day',
            field=models.IntegerField(default=0, verbose_name='잔여 연차일'),
        ),
    ]
