# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_agent_grant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': '대리인'},
        ),
        migrations.AlterModelOptions(
            name='grant',
            options={'verbose_name': '권한'},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': '사용자'},
        ),
        migrations.AlterModelOptions(
            name='usercode',
            options={'verbose_name': '직급코드'},
        ),
        migrations.AlterModelTable(
            name='agent',
            table='agents',
        ),
        migrations.AlterModelTable(
            name='grant',
            table='grants',
        ),
    ]
