# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('user_pw', models.CharField(max_length=255)),
                ('user_nm', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=50)),
                ('position', models.CharField(max_length=5)),
                ('v_day', models.IntegerField()),
                ('join_day', models.DateField()),
                ('exit_day', models.DateField()),
            ],
        ),
    ]
