# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('code_manager', '0001_initial'),
        ('team_manager', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_model',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('user_pw', models.CharField(max_length=255)),
                ('user_nm', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('v_day', models.IntegerField(null=True)),
                ('join_day', models.DateField()),
                ('exit_day', models.DateField(null=True)),
                ('birth', models.DateField(null=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('user_grade', models.CharField(max_length=10, null=True)),
                ('agent', models.CharField(max_length=20, null=True)),
                ('master', models.CharField(max_length=2, null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_code', to='code_manager.Code_model', to_field='cd')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_manager.Team_model')),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
