# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 02:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_type', models.CharField(choices=[('a', '연차'), ('b', '오전 반차'), ('c', '오후 반차'), ('d', '공가'), ('e', '병가'), ('e', '건강검진')], default='a', max_length=2, verbose_name='연차 종류')),
                ('start', models.DateField(verbose_name='연차 시작')),
                ('end', models.DateField(verbose_name='연차 끝')),
                ('first_approval', models.BooleanField(default=False, verbose_name='첫 승인 여부')),
                ('last_approval', models.BooleanField(default=False, verbose_name='마지막 승인 여부')),
                ('reason', models.TextField(verbose_name='사유')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '연차',
                'verbose_name_plural': '연차들',
                'db_table': 'vacations',
            },
        ),
    ]
