# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='vacation_type',
            field=models.CharField(choices=[('a', '연차'), ('b', '오전 반차'), ('c', '오후 반차'), ('d', '공가'), ('e', '병가'), ('e', '건강검진')], default='a', max_length=2, verbose_name='연차 종류'),
        ),
    ]
