# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0003_auto_20171109_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=10, verbose_name='연차 명')),
                ('minus_day', models.FloatField(verbose_name='차감일수')),
            ],
            options={
                'db_table': 'vacation_code',
            },
        ),
        migrations.AlterField(
            model_name='vacation',
            name='vacation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacations.VacationCode', verbose_name='연차 종류'),
        ),
    ]
