# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0004_auto_20171110_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='first_approval_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_approval_user', to='users.Grant', verbose_name='1차 승인자'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='last_approval_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_approval_user', to='users.Grant', verbose_name='최종 승인자'),
        ),
    ]
