# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 08:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0002_team_upper_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_master', to=settings.AUTH_USER_MODEL, verbose_name='그룹장'),
        ),
        migrations.AlterField(
            model_name='team',
            name='upper_team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.Team', verbose_name='상위그룹'),
        ),
    ]
